import { Router } from 'express';
import { authenticate } from '../middleware/auth';
import { authorize } from '../middleware/authorize';
import { upload } from '../utils/upload';
import {
  validateFileType,
  validateFileSize,
  scanFileContent,
  cleanupOnError
} from '../middleware/fileSecurity';
import { guardStudentWriteByAuthenticatedUser } from '../middleware/studentLifecycleGuard';
import * as documentController from '../controllers/document.controller';

const router = Router();

router.use(authenticate);

// Document upload and management
router.post('/upload',
  guardStudentWriteByAuthenticatedUser,
  upload.single('file'),
  validateFileType,
  validateFileSize,
  scanFileContent,
  cleanupOnError,
  documentController.uploadDocument
);
router.get('/', documentController.getDocuments);
router.get('/student', documentController.getStudentDocuments);
router.get('/student-picker', documentController.getStudentPickerList);
router.get('/:id', documentController.getDocumentById);
router.get('/:id/download', documentController.downloadDocument);
router.get('/:id/feedback', documentController.getDocumentFeedback);
router.put('/:id/approve', authorize(['COORDINATOR', 'INSTRUCTOR']), documentController.approveDocument);
router.put('/:id/reject', authorize(['COORDINATOR', 'INSTRUCTOR']), documentController.rejectDocument);
router.post(
  '/:id/feedback',
  authorize(['ADMIN', 'COORDINATOR', 'INSTRUCTOR', 'INDUSTRY_PARTNER', 'STUDENT']),
  documentController.addDocumentFeedback,
);
router.delete('/:id', authorize(['ADMIN', 'STUDENT']), guardStudentWriteByAuthenticatedUser, documentController.deleteDocument);

// Shared endorsement letter accept/decline
router.post('/:id/accept-shared', authorize(['STUDENT']), guardStudentWriteByAuthenticatedUser, documentController.acceptSharedDocument);
router.post('/:id/decline-shared', authorize(['STUDENT']), guardStudentWriteByAuthenticatedUser, documentController.declineSharedDocument);

// Form-based document generation
router.get('/form-definition/:type', documentController.getFormDefinition);
router.post('/preview', guardStudentWriteByAuthenticatedUser, documentController.previewDocument);
router.post('/finalize', guardStudentWriteByAuthenticatedUser, documentController.finalizeDocument);

// Auto-generate documents from existing system data
router.post('/generate-auto', authorize(['STUDENT']), guardStudentWriteByAuthenticatedUser, documentController.autoGenerateDocument);

export default router;